apiVersion: v2
kind: Application
metadata:
  name: nats
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after cert-manager
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.2.2  # Check for latest version
    helm:
      values: |
        # NATS Cluster Configuration
        config:
          cluster:
            enabled: true
            replicas: 3
            name: nats-cluster
          
          # Enable JetStream for persistence
          jetstream:
            enabled: true
            fileStore:
              pvc:
                size: 10Gi
                storageClassName: standard  # Adjust per environment
              dir: /data/jetstream
            memStore:
              enabled: true
              maxSize: 1Gi
          
          # Store directory for persistence
          storeDir: /data/nats
          
          # TLS Configuration
          tls:
            enabled: true
            secretName: nats-tls-cert  # From cert-manager
            ca: "ca.crt"
            cert: "tls.crt"
            key: "tls.key"
            verify: true
            
            # Client certificate verification
            verifyAndMap: false  # Set true if using mTLS
          
          # Monitoring
          monitoring:
            enabled: true
            port: 7777
          
          # Limits and resources
          limits:
            maxConnections: 64K
            maxSubscriptions: 0
            maxPayload: 1MB
            maxPending: 64MB
            writeDeadline: 10s
        
        # Pod configuration
        nats:
          image:
            repository: nats
            tag: 2.10-alpine
            pullPolicy: IfNotPresent
          
          # Resources - adjust per environment
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          
          # Pod anti-affinity for HA
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - nats
                topologyKey: kubernetes.io/hostname
        
        # Service Configuration
        service:
          enabled: true
          type: LoadBalancer
          ports:
            client:
              port: 4222
            monitoring:
              port: 8222
            cluster:
              port: 6222
            leafnodes:
              port: 7422
          
          # Annotations for cloud provider LB
          annotations:
            # AWS
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
            # GCP
            # cloud.google.com/load-balancer-type: "Internal"
            # Azure
            # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        
        # Enable Prometheus ServiceMonitor
        serviceMonitor:
          enabled: true
          labels:
            prometheus: kube-prometheus
          interval: 30s
          scrapeTimeout: 10s
        
        # NATS Box for debugging (optional)
        natsbox:
          enabled: true
          image:
            repository: natsio/nats-box
            tag: 0.14.1
          
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        
        # Reloader for config changes
        reloader:
          enabled: true
          image:
            repository: natsio/nats-server-config-reloader
            tag: 0.14.2
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 2  # For 3-node cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
