---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-ingester
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/name: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-querier
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: querier
      app.kubernetes.io/name: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-query-frontend
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/name: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-store-gateway
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: store-gateway
      app.kubernetes.io/name: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-distributor
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: distributor
      app.kubernetes.io/name: mimir
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-compactor
  namespace: mimir
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: compactor
      app.kubernetes.io/name: mimir
