apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
  # Source 1: Helm chart from Crossplane repo
  - repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.14.5
    helm:
      values: |
        # Enable the provider packages to be installed
        args:
          - --enable-composition-revisions

  # Source 2: Provider resources (Provider CRD, ProviderConfig, namespace)
  - repoURL: https://github.com/suckatrash/nats-argocd-stack.git
    targetRevision: HEAD
    path: environments/minimal/crossplane/provider

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
