apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-store
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    gcpsm:
      projectID: "PROJECT_ID_PLACEHOLDER"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            namespace: bootstrap-secrets
            key: secret-access-credentials
