apiVersion: v2
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before other apps
spec:
  project: platform
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
    helm:
      values: |
        installCRDs: true
        
        # Deploy webhook for secret validation
        webhook:
          enabled: true
          port: 9443
          
        # Cert-controller for webhook certificates
        certController:
          enabled: true
        
        # Resource settings
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        
        # Enable metrics
        serviceMonitor:
          enabled: true
          interval: 30s
        
        # Replicas for HA
        replicaCount: 2
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
# AWS Secrets Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      
      # Option 1: Use IRSA (recommended for EKS)
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      
      # Option 2: Use access keys (for non-EKS or initial setup)
      # auth:
      #   secretRef:
      #     accessKeyID:
      #       name: aws-credentials
      #       key: access-key-id
      #     secretAccessKey:
      #       name: aws-credentials
      #       key: secret-access-key

---
# GCP Secret Manager SecretStore
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    gcpsm:
      projectID: "your-gcp-project-id"
      
      # Option 1: Use Workload Identity (recommended for GKE)
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: your-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      
      # Option 2: Use service account key
      # auth:
      #   secretRef:
      #     secretAccessKeyRef:
      #       name: gcp-credentials
      #       key: secret-access-credentials

---
# Azure Key Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    azurekv:
      vaultUrl: "https://your-keyvault.vault.azure.net"
      
      # Option 1: Managed Identity (recommended for AKS)
      authType: ManagedIdentity
      
      # Option 2: Service Principal
      # authType: ServicePrincipal
      # authSecretRef:
      #   clientId:
      #     name: azure-credentials
      #     key: client-id
      #   clientSecret:
      #     name: azure-credentials
      #     key: client-secret
      # tenantId: "your-tenant-id"

---
# HashiCorp Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      
      # Kubernetes auth method
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      
      # Or AppRole auth
      # auth:
      #   appRole:
      #     path: "approle"
      #     roleId: "role-id-here"
      #     secretRef:
      #       name: vault-approle
      #       key: secretId
