---
# External Secrets Operator Helm Release
apiVersion: v2
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Install before everything else
spec:
  project: platform
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
    helm:
      values: |
        installCRDs: true
        
        webhook:
          port: 9443
        
        replicaCount: 2
        
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        serviceMonitor:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
