apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orders-nats-creds
  namespace: order-pipeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store
  target:
    name: orders-nats-creds
    creationPolicy: Owner
  data:
    - secretKey: admin.creds
      remoteRef:
        key: orders-admin-creds
