apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-store
  annotations:
    # Deploy ClusterSecretStore early so ExternalSecrets can use it
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider:
    gcpsm:
      # This gets patched by kustomization.yaml with your actual project ID
      projectID: "PROJECT_ID"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            # Use bootstrap-secrets namespace to persist across ArgoCD app deletions
            namespace: bootstrap-secrets
            key: secret-access-credentials