apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-store
spec:
  provider:
    gcpsm:
      projectID: "erik-sandbox-408216"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            namespace: external-secrets
            key: secret-access-credentials