apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-pdc-agent
  namespace: pdc-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store
  target:
    name: grafana-pdc-agent
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: grafana-pdc-token
