apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-ingress-nginx'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: ingress-nginx
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.9.0
        helm:
          valuesObject:
            controller:
              resources:
                requests:
                  cpu: 100m
                  memory: 90Mi
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-cert-manager'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: cert-manager
      source:
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.14.4
        helm:
          valuesObject:
            installCRDs: true
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: external-dns@{{.gcp.project}}.iam.gserviceaccount.com
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-cert-manager-issuers'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: cert-manager
      source:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        targetRevision: HEAD
        path: base/cert-manager
        kustomize:
          patches:
            - target:
                kind: ClusterIssuer
                name: letsencrypt-prod
              patch: |
                - op: replace
                  path: /spec/acme/email
                  value: '{{.certManager.email}}'
            - target:
                kind: ClusterIssuer
                name: letsencrypt-staging
              patch: |
                - op: replace
                  path: /spec/acme/email
                  value: '{{.certManager.email}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-crossplane'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: crossplane-system
      source:
        repoURL: https://charts.crossplane.io/stable
        chart: crossplane
        targetRevision: 1.14.5
        helm:
          valuesObject:
            args:
              - --enable-composition-revisions
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-crossplane-providers'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: crossplane-system
      source:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        targetRevision: HEAD
        path: base/crossplane-providers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane-config
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-crossplane-config'
      annotations:
        argocd.argoproj.io/sync-wave: "4"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: crossplane-system
      source:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        targetRevision: HEAD
        path: base/crossplane-config
        kustomize:
          patches:
            - target:
                kind: ProviderConfig
                name: default
              patch: |
                - op: replace
                  path: /spec/projectID
                  value: '{{.gcp.project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-external-secrets'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: external-secrets
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.9.13
        helm:
          valuesObject:
            installCRDs: true
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-stores
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-external-secrets-stores'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: external-secrets
      source:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        targetRevision: HEAD
        path: base/external-secrets
        kustomize:
          patches:
            - target:
                kind: ClusterSecretStore
                name: gcpsm-cluster-store
              patch: |
                - op: replace
                  path: /spec/provider/gcpsm/projectID
                  value: '{{.gcp.project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/suckatrash/nats-argocd-stack.git
        revision: HEAD
        files:
          - path: "clusters/*/config.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-external-dns'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      destination:
        server: '{{.cluster.server}}'
        namespace: external-dns
      source:
        repoURL: https://kubernetes-sigs.github.io/external-dns
        chart: external-dns
        targetRevision: 1.15.0
        helm:
          valuesObject:
            provider: google
            google:
              project: '{{.gcp.project}}'
              serviceAccountSecret: ""
            domainFilters:
              - '{{.dns.baseDomain}}'
            txtOwnerId: "external-dns"
            txtPrefix: "_external-dns."
            sources:
              - ingress
              - service
            policy: sync
            interval: 1m
            logLevel: info
            registry: txt
            serviceAccount:
              create: true
              annotations:
                iam.gke.io/gcp-service-account: 'external-dns@{{.gcp.project}}.iam.gserviceaccount.com'
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 50m
                memory: 64Mi
            extraArgs:
              - --google-zone-visibility=public
              - '--zone-id-filter={{.dns.zoneName}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
