apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: control-plane-db-password
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-cluster-store
    kind: ClusterSecretStore
  target:
    name: control-plane-db-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: control-plane-db-password
