apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-dsn-creator
  namespace: control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-dsn-creator
  namespace: control-plane
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-dsn-creator
  namespace: control-plane
subjects:
  - kind: ServiceAccount
    name: postgres-dsn-creator
    namespace: control-plane
roleRef:
  kind: Role
  name: postgres-dsn-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-dsn
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: postgres-dsn-creator
      containers:
        - name: create-dsn
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e

              echo "Waiting for control-plane-db-connection secret..."
              until kubectl get secret control-plane-db-connection -n control-plane &>/dev/null; do
                echo "Secret not found, waiting..."
                sleep 5
              done

              echo "Waiting for control-plane-db-password secret..."
              until kubectl get secret control-plane-db-password -n control-plane &>/dev/null; do
                echo "Secret not found, waiting..."
                sleep 5
              done

              HOST=$(kubectl get secret control-plane-db-connection -n control-plane -o jsonpath='{.data.privateIP}' | base64 -d)
              PASSWORD=$(kubectl get secret control-plane-db-password -n control-plane -o jsonpath='{.data.password}' | base64 -d)
              URL_ENCODED_PASSWORD=$(printf %s "$PASSWORD" | jq -sRr @uri)

              DSN="postgres://control-plane-scp-user:${URL_ENCODED_PASSWORD}@${HOST}:5432/control-plane-scpdata?sslmode=verify-ca&sslcert=/app/db-certs/client-cert.pem&sslkey=/app/db-certs/client-key.pem&sslrootcert=/app/db-certs/server-ca.pem"

              kubectl create secret generic control-plane-postgres-dsn \
                -n control-plane \
                --from-literal=postgres-dsn="$DSN" \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "PostgreSQL DSN secret created successfully"
