apiVersion: batch/v1
kind: Job
metadata:
  name: generate-postgres-password
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: secret-generator
      containers:
        - name: generate-password
          image: google/cloud-sdk:alpine
          command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache openssl curl

              echo "Fetching project ID from metadata server..."
              PROJECT_ID=$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id" 2>/dev/null || echo "")

              if [ -z "$PROJECT_ID" ]; then
                echo "Error: Could not retrieve project ID from metadata server"
                exit 1
              fi

              echo "Using project: $PROJECT_ID"

              SECRET_NAME="control-plane-db-password"

              echo "Getting access token..."
              ACCESS_TOKEN=$(curl -s -H "Metadata-Flavor: Google" \
                "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" | \
                grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)

              if [ -z "$ACCESS_TOKEN" ]; then
                echo "Error: Could not retrieve access token"
                exit 1
              fi

              echo "Checking if secret already exists..."
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$SECRET_NAME")

              if [ "$STATUS" = "200" ]; then
                echo "Secret $SECRET_NAME already exists, skipping generation"
                exit 0
              fi

              echo "Generating new database password..."
              PASSWORD=$(openssl rand -base64 32)

              echo "Creating secret in GCP Secret Manager..."
              curl -s -X POST \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Content-Type: application/json" \
                "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets?secretId=$SECRET_NAME" \
                -d '{"replication": {"automatic": {}}}'

              curl -s -X POST \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "Content-Type: application/json" \
                "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$SECRET_NAME:addVersion" \
                -d "{\"payload\": {\"data\": \"$(echo -n "$PASSWORD" | base64 -w0)\"}}"

              echo "Database password generated and stored successfully"
