apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-plane-data
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
