apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator
  namespace: control-plane
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-sa@PROJECT_ID_PLACEHOLDER.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
  - kind: ServiceAccount
    name: secret-generator
    namespace: control-plane
roleRef:
  kind: Role
  name: secret-generator
  apiGroup: rbac.authorization.k8s.io
