---
# ExternalSecret to create docker-registry secret from GCP Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: control-plane
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcpsm-cluster-store
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
  - secretKey: username
    remoteRef:
      key: control-plane-ghcr-username
  - secretKey: token
    remoteRef:
      key: control-plane-ghcr-token
