---
# Job to generate KMS key and store in GCP Secret Manager
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-kms-key
  namespace: control-plane
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: kms-key-generator
      containers:
      - name: generate-key
        image: google/cloud-sdk:alpine
        command:
        - /bin/sh
        - -c
        - |
          set -e

          # Install openssl (not included in alpine base image)
          apk add --no-cache openssl

          PROJECT_ID=$(gcloud config get-value project)
          SECRET_NAME="control-plane-kms-key"

          # Check if secret already exists
          if gcloud secrets describe $SECRET_NAME --project=$PROJECT_ID &>/dev/null; then
            echo "Secret $SECRET_NAME already exists, skipping generation"
            exit 0
          fi

          echo "Generating new KMS key..."
          # Generate 32-byte (256-bit) random key and base64 encode it
          KEY=$(openssl rand -base64 32)

          # Store in base64key:// format as expected by control-plane
          KEY_URL="base64key://$KEY"

          echo "Creating secret in GCP Secret Manager..."
          echo -n "$KEY_URL" | gcloud secrets create $SECRET_NAME \
            --data-file=- \
            --replication-policy=automatic \
            --project=$PROJECT_ID

          echo "KMS key generated and stored successfully"
          echo "Key URL: $KEY_URL"
---
# ServiceAccount for the job (uses Workload Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kms-key-generator
  namespace: control-plane
  annotations:
    # This gets patched by kustomization.yaml with your actual project ID
    iam.gke.io/gcp-service-account: external-secrets@PROJECT_ID.iam.gserviceaccount.com
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
