---
# Job to generate PostgreSQL password and store in GCP Secret Manager
# Runs early (wave -1) to ensure password exists before User resource is created
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-postgres-password
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # Clean up completed jobs after 1 hour
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: secret-generator
      containers:
      - name: generate-password
        image: google/cloud-sdk:alpine
        command:
        - /bin/sh
        - -c
        - |
          set -e

          # Install required tools
          apk add --no-cache openssl curl

          # Get project ID from metadata server (works with Workload Identity)
          echo "Fetching project ID from metadata server..."
          PROJECT_ID=$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/project/project-id" 2>/dev/null || echo "")

          if [ -z "$PROJECT_ID" ]; then
            echo "Error: Could not retrieve project ID from metadata server"
            exit 1
          fi

          echo "Using project: $PROJECT_ID"

          # Verify workload identity is working
          echo "Verifying service account..."
          SA_EMAIL=$(curl -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email" 2>/dev/null || echo "")
          echo "Service account: $SA_EMAIL"

          SECRET_NAME="control-plane-db-password"

          # Get access token from metadata server
          echo "Getting access token..."
          ACCESS_TOKEN=$(curl -s -H "Metadata-Flavor: Google" \
            "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" | \
            grep -o '"access_token":"[^"]*"' | cut -d'"' -f4)

          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Error: Could not retrieve access token"
            exit 1
          fi

          # Check if secret already exists using REST API
          echo "Checking if secret already exists..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$SECRET_NAME")

          if [ "$STATUS" = "200" ]; then
            echo "Secret $SECRET_NAME already exists, skipping generation"
            exit 0
          fi

          echo "Generating new database password..."
          # Generate 32-byte random password and base64 encode it
          PASSWORD=$(openssl rand -base64 32)

          echo "Creating secret in GCP Secret Manager using REST API..."
          # Create the secret using REST API
          CREATE_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets?secretId=$SECRET_NAME" \
            -d "{
              \"replication\": {
                \"automatic\": {}
              }
            }")

          echo "Create response: $CREATE_RESPONSE"
          if echo "$CREATE_RESPONSE" | grep -q "error"; then
            echo "Error creating secret: $CREATE_RESPONSE"
            exit 1
          fi

          # Add the secret version with the actual password data
          echo "Adding secret version..."
          VERSION_RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            "https://secretmanager.googleapis.com/v1/projects/$PROJECT_ID/secrets/$SECRET_NAME:addVersion" \
            -d "{
              \"payload\": {
                \"data\": \"$(echo -n "$PASSWORD" | base64 -w0)\"
              }
            }")

          echo "Version response: $VERSION_RESPONSE"
          if echo "$VERSION_RESPONSE" | grep -q "error"; then
            echo "Error adding secret version: $VERSION_RESPONSE"
            exit 1
          fi

          echo "Database password generated and stored successfully"
