---
# PostgreSQL Database Instance provisioned via Crossplane
# Starts provisioning at wave 1 (takes 5-10 minutes to become Ready)
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: control-plane-db
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  forProvider:
    region: us-west1
    databaseVersion: POSTGRES_16
    settings:
    - edition: ENTERPRISE
      tier: db-f1-micro
      diskSize: 10
      diskType: PD_SSD
      ipConfiguration:
      - ipv4Enabled: false
        privateNetwork: projects/PROJECT_ID/global/networks/default
      backupConfiguration:
      - enabled: true
        startTime: "03:00"
        pointInTimeRecoveryEnabled: true

  # Orphan the Cloud SQL instance if this K8s resource is deleted
  # This ensures the database persists through rebuilds
  deletionPolicy: Orphan

  # Store connection details in a secret
  writeConnectionSecretToRef:
    name: control-plane-db-connection
    namespace: control-plane

  providerConfigRef:
    name: default
---
# Database: scpdata
# Created after DatabaseInstance is ready (sync-wave 2)
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  name: control-plane-scpdata
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    instanceRef:
      name: control-plane-db

  # Orphan the database if this K8s resource is deleted
  # This ensures the database persists through rebuilds
  deletionPolicy: Orphan

  providerConfigRef:
    name: default
---
# User: control-plane-scp-user
# Created after DatabaseInstance is ready (sync-wave 2)
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: control-plane-scp-user
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    instanceRef:
      name: control-plane-db
    passwordSecretRef:
      name: control-plane-db-password
      namespace: control-plane
      key: password

  # User is NOT orphaned - it gets deleted/recreated on rebuilds
  # This ensures the Cloud SQL password is updated to match the secret
  # The password itself persists in GCP Secret Manager (generator job is idempotent)
  # Database and DatabaseInstance ARE orphaned, so encrypted data persists
  # KMS key persists in GCP Secret Manager, so encrypted data remains readable

  providerConfigRef:
    name: default
