---
# Allow secret-generator service account to manage secrets
# Needed by db-client-cert-job to store client certificates
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-generator
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-generator
  namespace: control-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
- kind: ServiceAccount
  name: secret-generator
  namespace: control-plane
roleRef:
  kind: Role
  name: secret-generator
  apiGroup: rbac.authorization.k8s.io
