apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-config
  namespace: insights
data:
  insights.yaml: |
    nats:
      url: nats://CLUSTER_NAME-nats.nats.svc.cluster.local:4222
      creds: /etc/insights/creds/sys.creds
    data-dir: /data
    scraper:
      interval: 1m
    log-level: info
