apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: insights-nats-creds
  namespace: insights
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store
  target:
    name: insights-nats-creds
    creationPolicy: Owner
  data:
    - secretKey: sys.creds
      remoteRef:
        key: insights-sys-creds
