apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insights-data
  namespace: insights
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi
